login_url: 'https://test-stand.gb.ru/gateway/login'
post_url: 'https://test-stand.gb.ru/api/posts'
username: 'Penguin_1'
password: '746a1d6764'
post_title: 'Домашняя работа №1'
post_description: 'Как я мучался'
post_content: 'Это было просто ужасно, но интересно'
